Person ::= ( identifier )* ( living | ) ( gender | ) ( name )* ( fact )* ( source )* ( note )*
Relationship ::= type person1 person2 ( fact )* ( source )* ( note )*
identifier ::= type resource
living ::= ( <true> | <false> )
gender ::=  conclusion_properties type
name ::= conclusion_properties type primaryForm ( alternateForm )* ( preferred | )
fact ::= conclusion_properties type ( date | ) ( place | ) ( original | ) ( formal | )
date ::= original formal
place ::= original formal
original ::= text
primaryForm ::= nameForm
alternateForm ::= nameForm
nameForm ::= ( fullText | ) ( namePart )*
namePart ::= type text
preferred ::= ( <true> | <false> )
conclusion_properties ::= genealogical_resource_properties ( source )*
genealogical_resource_properties ::= ( id | ) attribution
attribution ::= ( contributor | ) ( confidence | ) ( modified | ) ( proofStatement | )
formal ::= ( value | ) ( datatype | ) ( resource_reference | )
resource_reference ::= resource
resource ::= URI
contributor ::= resource_reference
type ::= resource_reference
note ::= ( lang | ) text